server:
  port: 8090
spring:
  application:
    name: redisTemplate_test
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为loaclhost）
    host: 192.168.31.129
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: root
    # redis连接超时时间（单位毫秒）
    timeout: 0
    # redis连接池配置
    lettuce:
      pool:
        #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
        maxActive: 600
        #最大空闲数
        maxIdle: 200
        minIdle: 0
        #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
        maxTotal: 1000
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        maxWaitMillis: 5000
